spring:
  profiles:
    active: dev
 #配置日志
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  #配置日志文件路径
  file: log\epay.log
  file.max-size: 100MB
  #配置日志文件输出级别
  level:
    root: INFO
    org.hibernate: error